### ISSUE TITLE
Two kid.png files creates trouble on macOS

### ISSUE THREAD

**Issue by gosh-darn** [ctrlcctrlv/chomsky#10]
I have the repository cloned to my MacBook, where there can only exist a single file with the name kid.png, regardless of capitalization. This creates a file conflict which is impossible to solve in the current state.

I’d recommend renaming them kid-1.png and kid-2.png or something similiar; I’d consider it best practise.

<img width="1792" alt="Screenshot 2020-11-13 at 18 18 13" src="https://user-images.githubusercontent.com/26469320/99101260-a1a65f00-25dc-11eb-9af0-6de539294020.png">

**Comment by ctrlcctrlv** [comment]
If you wish to push a change, I'm happy to accept a commit as part of the PR which deletes the lower resolution version (kid.png).
