### ISSUE TITLE
The small “ł” is exactly the same as the letter “l”

### ISSUE THREAD

**Issue by thebodzio** [ctrlcctrlv/chomsky#2]
The small “ł” is exactly the same as the letter “l”, while it should have an oblique stroke through it—similar to the capital “Ł”.

**Comment by ctrlcctrlv** [comment]
Oh, yes I do see that—oops. I'll upload a quick fix as soon as I can.

**Comment by thebodzio** [comment]
Thank you! It is most appreciated!

**Comment by ctrlcctrlv** [comment]
Fixed in https://github.com/ctrlcctrlv/chomsky/commit/7baae440d1e278a1f91a7dcb428f53373cc27ab8

Sorry about that, thanks for using my font! _Dziękuję bardzo!_

**Comment by thebodzio** [comment]
There is absolutely nothing to be sorry for. Instead, it is me who should be grateful for your splendid and hard work, which I truly am. I also appreciate a little Polish touch in your last post. It is always heartwarming to see.

Thank you again for your effort! God bless!
