### ISSUE TITLE
CE support and some glyph fixes

### ISSUE THREAD

**Issue by 2CLC** [ctrlcctrlv/chomsky#3]
Hi Fredrick,
thanks for lots of work and an awesome share with Chomsky.

I have found some issues with some CE glyphs, especially lcaron, Lcaron, dcaron and tcaron so I fixed them at least partially.

Since I don't use FontForge, but FontLab, I assume you can fetch the changes directly from the re-compiled .otf you can find [here](https://github.com/2CLC/chomsky/blob/master/dist/Chomsky%20CE.otf).
I correctly renamed my modified font file since it's not the original one and original sources weren't used to make the modifications.

**Comment by ctrlcctrlv** [comment]
I read online that those glyphs are often written with ^ in handwriting, and in certain typewriters. I'd consider a blackletter font to be a type of handwriting. I actually changed FontForge to make it the way I did on purpose.

**Comment by 2CLC** [comment]
Acutally nope.
Those glyphs are never written with ^, not in handwriting, just the old typewriters, that were modified from the original german ones to support CE characters, had it that way, but it wasn't typographically correct.

For reference I'm linking two examples ([1](https://www.stormtype.com/families/dracula?utf8=%E2%9C%93&pangram=2)), ([2](https://www.stormtype.com/families/wittingau?utf8=%E2%9C%93&pangram=2))  of blackletter fonts with correct accented characters from a professional typographer, an professor of Typography at The Academy of Arts, Architecture & Design in Prague, František Štorm.
Feel free to check them out.
![wittingau-example](https://user-images.githubusercontent.com/54023864/62860607-f172e800-bd00-11e9-9a17-97fe1a07e2c2.gif)
![dracula-example](https://user-images.githubusercontent.com/54023864/62860608-f172e800-bd00-11e9-9020-7d1bbf68ae2c.gif)

**Comment by 2CLC** [comment]
I'll also add that in Chomsky, the accented glyps with acute are way lighter than those with carons, you might want to downsize the carons a bit (carons are also way bigger than acutes, bout should share the same weight).

**Comment by ctrlcctrlv** [comment]
Hi friend,

Thanks for the info. I still have questions. Obviously this isn't a language I speak, I don't even exactly remember which language uses these glyphs.

Can you please read over https://github.com/fontforge/fontforge/pull/3617#issuecomment-479257557 and https://github.com/fontforge/fontforge/pull/3617#issuecomment-479260505 ? It's based on that document and that image that I chose to make the caron v-shaped.

Thanks. Sorry to bother you, I am just trying to figure out who is wrong here, if it's the Unicode people or you, or if blackletter just doesn't count as handwriting.

**Comment by ctrlcctrlv** [comment]
I'm also working on a typewriter font right now so if you could answer for that case too. I want it to look like a vintage typewriter. I found this precedent for that https://github.com/fontforge/fontforge/pull/3617#issuecomment-479263320

**Comment by ctrlcctrlv** [comment]
Could the problem be that I primarily considered dcaron (&dcaron;), but you seem to mostly be considering tcaron (&tcaron;)?

**Comment by 2CLC** [comment]
Hi again,
lcaron and Lcaron are specific for Slovak language only.
dcaron and tcaron are used in Czech language (and some others as well).

Statement from [link you have shared](https://github.com/fontforge/fontforge/pull/3617#issuecomment-479257557) are incorrect. Háček (aca caron) is never preferred (in case of tcaron, lcaron, Lcaron or dcaron) since it is against typographic rules.
_Edit: In fact, "klička" is preferred (seems like a rounded apostrophe) for those glyphs._

The example you shared [here](https://github.com/fontforge/fontforge/pull/3617#issuecomment-479260505) is from an old and outdated elementary school book and doesn't apply to any actual font for printing. It's made to avoid confusing children and is not used for over a decade (Check following link that goes into the issue, with examples. On page 28, 40, 55, 118) you can see corresponding glyphs  in a font that's currently used by Czech schools - Comenia Script - it is used as a template to teach kids to write correctly today - [How to use Comenia Script](http://www.lencova.eu/download/Lencova_Comenia_Script-short%E2%80%932013.pdf) from a site dedicated to the official czech school script font - [Comenia Script](http://www.comeniascript.cz/)

**Comment by ctrlcctrlv** [comment]
Thanks!

Yes, I see that. Can't really argue with page 55 of [this PDF](http://www.lencova.eu/download/Lencova_Comenia_Script-short%E2%80%932013.pdf).

Unfortunately, I can't use the work you did in this project, but I'm sure you can. I'll have to port what you did to FontForge when I have time. It should be pretty simple. I'll also keep in mind that note about the size of the carons.

Sorry for the inconvenience, I was trying my best to do it right but when the information in English isn't very good mistakes will be made :-) Especially if there's no information in any of the other languages I speak either. :-P

**Comment by 2CLC** [comment]
Oh, you did a great job, Fredrick, I'm pretty astonished how good your work is, considering you are quite new to font creation. You're awesome (but you already know).
I, once again, have to thank you for incredible job you did on the project and will certainly keep an eye on you and your future projects.
