### ISSUE TITLE
"Masthead" is the wrong word

### ISSUE THREAD

**Issue by MrShiv** [ctrlcctrlv/chomsky#4]
The “masthead” of a publication is the box that lists its staff, editor, etc., NOT the title on the front page, which is properly referred to as the “banner” (or sometimes “flag”). This is a very common error

**Comment by schainks** [comment]
Seconded. "Logo" could also be used, as well as "banner" or "flag".

**Comment by ctrlcctrlv** [comment]
_[The Guardian](http://image.guardian.co.uk/sys-files/Guardian/documents/2011/08/26/EducCentNewsterminology.pdf)_ disagrees.

It could be a UK/US English difference, and not an error.
