### ISSUE TITLE
[request] R rotunda

### ISSUE THREAD

**Issue by nikita-moor** [ctrlcctrlv/chomsky#5]
Could you add, please, glyphs for R rotunda:

* U+A75A Ꝛ LATIN CAPITAL LETTER R ROTUNDA
* U+A75B ꝛ LATIN SMALL LETTER R ROTUNDA

It's used in the abbreviation "ꝛc" (= etc.) in blackletter scripts. There is a good example in [Wikipedia][1].

![image](https://user-images.githubusercontent.com/13879891/75633333-f6ec3d00-5c14-11ea-9918-ac716505bc05.png)

Also, "double oblique hyphen" form of the hyphen (U+002D) may look better in blackletter fonts (see [Wiki][2]), but I'm not a designer and can't affirm that it fits well for Chomsky font. Hope, you will take a look.

![image](https://user-images.githubusercontent.com/13879891/75633350-14b9a200-5c15-11ea-84c7-b1670620dbd3.png)

[1]: https://en.wikipedia.org/wiki/R_rotunda
[2]: https://en.wikipedia.org/wiki/Double_hyphen

**Comment by nikita-moor** [comment]
Was solved in the fork: https://github.com/nikita-moor/chomsky

**Comment by ctrlcctrlv** [comment]
Please don't close issues.

**Comment by ctrlcctrlv** [comment]
@nikita-moor Most likely I'll cherry-pick 21aed4b760d203077597c586ca5255ccf0add522 with my own commit on top adding you to the README. Is this acceptable to you?

**Comment by ctrlcctrlv** [comment]
(I would then release Chomsky v1.4)

**Comment by nikita-moor** [comment]
Yes, sure.

**Comment by ctrlcctrlv** [comment]
Cool. In future, you can submit PRs as well if you improve it more :-)

**Comment by ctrlcctrlv** [comment]
Fixed in v2.0

![](https://raw.githubusercontent.com/ctrlcctrlv/chomsky/master/tex/v2.0.png)
