### ISSUE TITLE
[bug] combining tilde over M

### ISSUE THREAD

**Issue by nikita-moor** [ctrlcctrlv/chomsky#6]
Character 'COMBINING TILDE' (U+0303) generally works well, but being placed on "m" it shifts to the following letter:

![image](https://user-images.githubusercontent.com/13879891/76766081-7f87e300-67a8-11ea-9f86-e5dff55738f6.png)

Here all but the last words are correct, in "Kunstkam̃er" tilde should be above "m", not "e".

P.S. In old German books (XVIII c.) tilde is used similarly to modern Portuguese for nasalization and reduplication:
- Kunstkam̃er > Kunstkammer
- autẽ > autem

**Comment by nikita-moor** [comment]
Was solved in the fork: https://github.com/nikita-moor/chomsky

**Comment by ctrlcctrlv** [comment]
Fixed in v2.0

![](https://raw.githubusercontent.com/ctrlcctrlv/chomsky/master/tex/v2.0.png)
