### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by dags99** [ctrlcctrlv/chomsky#7]
Sorry I don’t use this website very well but it’s okay actually is not a issue I really like your work and everything is okay  the thing is I want to start a brand of clothes With this letting On the logo but I not sure, for the legal reasons so I want to now if I can used Or what you know about it 
Thank you and I’ll waiting for your answer 
Have a good one

**Comment by ctrlcctrlv** [comment]
Everything I know about the legal aspects is in the Readme. More specialized advice will need to come from a real attorney
